#!/bin/bash
#./dump1090 --gain 49.6 --net  --fix --phase-enhance --aggressive --interactive --metric --interactive-rows 100 --interactive-ttl 10 --r_max 300 --sort 0 --ppm -21 --r_min 5 --az_start 0 --az_stop 360 --pathname data


#./dump1090 --gain 49.6 --net --aggressive --fix --phase-enhance --interactive --interactive-rows 100 --interactive-ttl 10  --net-sbs-port 30003 --net-ro-port 31001  --lat 32.053459 --lon 118.728264  --height 31.0  --write-json data --json-location-accuracy 2 --dcfilter --udp-mcast_ip 230.1.1.1 --udp-mcast_port 7838 --udp-my_ip 192.168.100.1 --udp-my_port 12345


#"--udp-mcast_ip          ip address to multicast the airplane's info\n"
#"--udp-mcast_port      ip port to udp-multicast the airplane's info\n"
#"--udp-my_ip               my ip address to for multicasting the airplane's info\n(Default is IP of the host)"
#"--udp-my_port          my port for address to multicast the airplane's info\n(Defalut is 23456)" #jufuyuan

./dump1090 --quiet --interactive  --gain 49.6 --net --aggressive --fix --phase-enhance   --net-sbs-port 30003 --net-ro-port 31001  --lat 32.053459 --lon 118.728264  --height 31.0  --write-json data --json-location-accuracy 2 --dcfilter  --udp-mcast-ip 230.1.1.1 --udp-mcast-port 7838   --selectedfile data/select.txt # --udp-my_ip 192.168.100.1 --udp-my_port 12345 #jufuyuan

#--lat  31.95674405 --lon 119.2188767 #jurong



####  the value for  --ppm is obtained by kal
# --pathname data
#./dump1090 --aggressive --interactive 
